package SoseL21.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class BinaryInteger_Constraints extends BaseConstraintsDescriptor {
  public BinaryInteger_Constraints() {
    super(CONCEPTS.BinaryInteger$dJ);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BinaryInteger$dJ = MetaAdapterFactory.getConcept(0x553bdaad1cb3493bL, 0xaccb16ef149d741aL, 0x52ab125ed6750519L, "SoseL21.structure.BinaryInteger");
  }
}
