package SoseL21.plugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.HashMap;

public class ValueInWorksheet {
  public static SNode BASE_NODE = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, "jetbrains.mps.lang.core.structure.BaseConcept"));
  private HashMap<String, Integer> intValues = new HashMap<>();
  public void saveIntValue(String name, int value) {
    intValues.put(name, value);
  }
  public int getIntValue(String name) {
    return intValues.get(name);
  }
}
