package SoseL21.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Assertion = 0;
  public static final int AssignBoolean = 1;
  public static final int AssignInteger = 2;
  public static final int BinaryBoolean = 3;
  public static final int BinaryInteger = 4;
  public static final int BolleanReturn = 5;
  public static final int Boolean = 6;
  public static final int BooleanExpression = 7;
  public static final int BooleanLetter = 8;
  public static final int BooleanParam = 9;
  public static final int BooleanReference = 10;
  public static final int CallFunction = 11;
  public static final int Class = 12;
  public static final int ClassCallFunction = 13;
  public static final int ClassConstructor = 14;
  public static final int Declaration = 15;
  public static final int Divide = 16;
  public static final int Expression = 17;
  public static final int ExpressionStatementContent = 18;
  public static final int For = 19;
  public static final int Function = 20;
  public static final int FunctionBool = 21;
  public static final int FunctionInteger = 22;
  public static final int Greater = 23;
  public static final int GreaterEqual = 24;
  public static final int IStatementContent = 25;
  public static final int IfElse = 26;
  public static final int Initializor = 27;
  public static final int Integer = 28;
  public static final int IntegerExpression = 29;
  public static final int IntegerLetter = 30;
  public static final int IntegerParam = 31;
  public static final int IntegerReference = 32;
  public static final int IntegerReturn = 33;
  public static final int Less = 34;
  public static final int LessEqual = 35;
  public static final int Minus = 36;
  public static final int Multiply = 37;
  public static final int NotEqual = 38;
  public static final int Object = 39;
  public static final int Parameter = 40;
  public static final int ParenExpression = 41;
  public static final int Plus = 42;
  public static final int ReferBooleanParam = 43;
  public static final int ReferIntegerParam = 44;
  public static final int Return = 45;
  public static final int SoSeWorksheet = 46;
  public static final int TestSuite = 47;
  public static final int Variable = 48;
  public static final int While = 49;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x553bdaad1cb3493bL, 0xaccb16ef149d741aL);
    builder.put(0x3b001b0bbabed2c2L, Assertion);
    builder.put(0x52ab125ed673d8ffL, AssignBoolean);
    builder.put(0x52ab125ed6705413L, AssignInteger);
    builder.put(0x27886c5347c15db5L, BinaryBoolean);
    builder.put(0x52ab125ed6750519L, BinaryInteger);
    builder.put(0x783263aad943765eL, BolleanReturn);
    builder.put(0xbfd127414c1ae46L, Boolean);
    builder.put(0x403c8839c2e6bde3L, BooleanExpression);
    builder.put(0x27886c5347c180d2L, BooleanLetter);
    builder.put(0x783263aad93fd8f3L, BooleanParam);
    builder.put(0x550d21c8a2e4a3eL, BooleanReference);
    builder.put(0x783263aad9437780L, CallFunction);
    builder.put(0x783263aad9404269L, Class);
    builder.put(0x3fb7e234ed94e3e8L, ClassCallFunction);
    builder.put(0x783263aad940425eL, ClassConstructor);
    builder.put(0x783263aad93fd602L, Declaration);
    builder.put(0x52ab125ed6758010L, Divide);
    builder.put(0x550d21c8a2e5f49L, Expression);
    builder.put(0x403c8839c2edc924L, ExpressionStatementContent);
    builder.put(0x783263aad93b98b1L, For);
    builder.put(0x783263aad93eaaa4L, Function);
    builder.put(0x783263aad93fd671L, FunctionBool);
    builder.put(0x783263aad93fd7a5L, FunctionInteger);
    builder.put(0x783263aad90b2b50L, Greater);
    builder.put(0x783263aad90b2b4dL, GreaterEqual);
    builder.put(0xbfd127414bf7cffL, IStatementContent);
    builder.put(0x783263aad93e3187L, IfElse);
    builder.put(0x352459422d1d9282L, Initializor);
    builder.put(0xbfd127414c0f1f7L, Integer);
    builder.put(0x403c8839c2e6bde4L, IntegerExpression);
    builder.put(0x52ab125ed67b2894L, IntegerLetter);
    builder.put(0x783263aad93fda43L, IntegerParam);
    builder.put(0xbfd127414c2cb91L, IntegerReference);
    builder.put(0x783263aad9437506L, IntegerReturn);
    builder.put(0x783263aad90b2b52L, Less);
    builder.put(0x783263aad90b2b51L, LessEqual);
    builder.put(0x52ab125ed675800fL, Minus);
    builder.put(0x52ab125ed6758011L, Multiply);
    builder.put(0x783263aad90b2b53L, NotEqual);
    builder.put(0x3fb7e234edb96592L, Object);
    builder.put(0x783263aad93ead20L, Parameter);
    builder.put(0x52ab125ed67b28a7L, ParenExpression);
    builder.put(0x52ab125ed675800eL, Plus);
    builder.put(0x783263aad93fdba2L, ReferBooleanParam);
    builder.put(0x783263aad9430a26L, ReferIntegerParam);
    builder.put(0x783263aad93eae03L, Return);
    builder.put(0xbfd127414bf7d02L, SoSeWorksheet);
    builder.put(0x3b001b0bbabecf48L, TestSuite);
    builder.put(0x403c8839c2e98e44L, Variable);
    builder.put(0x783263aad93e941dL, While);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
