package SoseL21.runtime;

/*Generated by MPS */


public class map_toJavaCode {
  public boolean test_int_1;
  public boolean test_int_2;
  public boolean test_bool;
  public boolean ;
  public boolean ;
  public boolean add;
  public boolean sumUtil;
  public boolean or;
  public int test_int_1;
  public int test_int_2;
  public int test_bool;
  public int ;
  public int ;
  public int add;
  public int sumUtil;
  public int or;

}
